### PR TITLE
Update tdd exercise to use replit

### PR DESCRIPTION
**Pull request by beccaelenzil**
TDD Exercise was in a github repo. However, students complete this exercise before they learn how to collaborate using git, so this PR moves in to a replit: https://replit.com/@adadev/tdd-exercise#README.md

### CODE REVIEW

**Review by CheezItMan — APPROVED** [review]
LGTM

**Review by kelsey-steven-ada — APPROVED** [review]
Looks good! I looked at the repl.it real quick & it looks like there may be a typo in the steps for part 2 in the README:

> Part 2: Identifying Edge & Nominal Cases
> In class, you will: 1. Review the test cases you identified in Part 1 1. Determine how you would test these cases

**Comment by beccaelenzil** [comment]
@kelsey-steven-ada Good catch! Fixed. Looks like a difference between how github and replit render markdown.

**Review by spitsfire — APPROVED** [review]
👍

**Pull request merged**
